kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test hello-world.go

- name: build
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go build hello-world.go

volumes:
- name: deps
  temp: {}