kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go test hello-world.go

- name: build
  image: golang
  volumes:
  - name: deps
    path: /go
  - name: build_output
    path: ./hello-world
  commands:
  - go build hello-world.go

- name: run
  image: golang
  volumes: 
  - name: build_output
    path: ./hello-world
  commands:
  - ./hello-world 

volumes:
- name: deps
  temp: {}
- name: build_output
  temp: {}