# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  Terraform-Testing:
    docker:
      - image: wata727/tflint:0.15.0
    # working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: tflint
          command: |
            cd terraform
            tflint
  Terraform-Plan:
    docker:
      - image: hashicorp/terraform:0.12.21
    steps:
      - checkout
      - run:
          name: Plan
          command: |
            echo "$GCP_CREDS_FILE" | base64 --decode > /tmp/creds.json
            cd terraform
            terraform init
            terraform plan -out=output/planfile
      - persist_to_workspace:
          root: output
          paths:
            - planfile
  Terraform-Apply:
    docker:
      - image: hashicorp/terraform:0.12.21
    steps:
      - attach_workspace:
          at: output
      - checkout
      - run:
          name: Apply
          command: |
            echo "$GCP_CREDS_FILE" | base64 --decode > /tmp/creds.json
            cd terraform
            terraform init
            terraform apply -auto-approve output/planfile

workflows:
  version: 2
  Terraform_Workflow:
    jobs:
      - Terraform-Testing
      - Terraform-Plan:
          requires:
            - Terraform-Testing
          filters:
            branches:
              only: master
      - Terraform-Apply:
          type: approval
          requires:
            - Terraform-Plan
          filters:
            branches:
              only: master