# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.14.1
    # working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - run:
          name: test
          command: | 
            echo 'Hello World!'
            echo 'This is the delivery pipeline'